### ISSUE TITLE
Investigate possible FUNMAN integration

### ISSUE THREAD

**Issue by fivegrant** [DARPA-ASKEM/pyciemss-service#28]
This issue is to determine:

- [ ] what does FUNMAN take as input?
- [ ] what does FUNMAN create as output?
- [ ] produce a set of example usages or point to them (e.g. from Sift's examples)
- [ ] assess FUNMAN run time under various conditions
- [ ] ideate on how FUNMAN should be integrated into the Terarium stack

**Comment by brandomr** [comment]
@fivegrant I added some detail to this issue

**Comment by brandomr** [comment]
For reference--this seems to be their latest demo notebook: https://github.com/ml4ai/funman/blob/hackathon/notebooks/funman_api_example.ipynb
