### ISSUE TITLE
Store pyro simulation object 

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/pyciemss-service#29]
This issue is to store the `pickle` file that that pyciemms produces which as I understand it is some kind of serialized pyro object. We need to store this blob so that we can use it downstream in the future.

**Comment by fivegrant** [comment]
Blocked by [the fact no object is currently returned by the interfaces](https://github.com/ciemss/pyciemss/issues/343)

**Comment by fivegrant** [comment]
This is now unblocked since we have updated to PyCIEMSS v0.0.3
