### ISSUE TITLE
Add Ensemble notebook examples to PyCIEMSS tests

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/pyciemss-service#33]
This issue is to implement the ensembling that @sabinala demoed in various notebooks. These are great backend test cases to codify here as a baseline for our ensemble capability.

See https://github.com/ciemss/pyciemss/tree/sa-ensemble-eval/notebook/ensemble_eval_sa for more detail

**Comment by fivegrant** [comment]
This issue was accidentally rewritten when it should have been a new one. Additionally, this issue is stale since we're considering adopting the `knowledge-middleware` model of scenario testing
