### ISSUE TITLE
Possibly incorrect type hinting in PyCIEMSS optimization interface

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/pyciemss-service#41]
In [pyciemss/PetriNetODE/interfaces.py](https://github.com/ciemss/pyciemss/blob/main/src/pyciemss/PetriNetODE/interfaces.py), the type hints for the functions `load_and_optimize_and_sample_petri_model` and `load_and_calibrate_and_optimize_and_sample_petri_model` appear to be incorrect.

The arguments `initial_guess` and `bounds` both have type hints `Iterable[float]` and default values `0.5` and `[[0.0], [1.0]]` respectively. Based on the context and examples, they may need to be replaced with 
* `initial_guess: Iterable[float] = [0.5]`
* `bounds: Iterable[Iterable[float]] = [[0.0], [1.0]]`

Unrelated: `load_and_calibrate_and_optimize_and_sample_petri_model` has the argument `deterministic_learnable_parameters` but it is missing from the docstring. Please fix this so one can read about what this argument does.

**Comment by anirban-chaudhuri** [comment]
We have resolved these issues in the pyciemss repository.
